cameras:
  - id: csi-0
    type: csi
    sensor_id: 0
    width: 1280
    height: 720
    fps: 30
    flip: 0
    inference:
      enabled: false
  - id: csi-1
    type: csi
    sensor_id: 1
    width: 1280
    height: 720
    fps: 30
    flip: 0
    inference:
      enabled: false
  - id: usb-front
    type: usb
    device: /dev/v4l/by-id/usb-Generic_USB_Camera-video-index0
    width: 1280
    height: 720
    fps: 30
    flip: 0
    inference:
      enabled: false
